joystick_relay:
  ros__parameters:
    priority: True
    turbo:
      linear_forward_min  : 0.1
      linear_forward_max  : 0.5
      linear_backward_min : 0.1
      linear_backward_max : 0.5
      angular_min : 0.2
      angular_max : 1.7
      steps       : 3